#!/bin/bash

    HOSTNAME=$(hostname)

    source /etc/os-release
    OS="$PRETTY_NAME"

    UPTIME=$(uptime -p)

    CPU=$(lshw -class processor | grep -m 1 'product' | cut -d ':' -f 2 | sed 's/^[ \t]*//')
    CPU_SPEED=$(lshw -class processor | grep -m 1 'capacity' | cut -d ':' -f 2 | sed 's/^[ \t]*//')

    RAM=$(free -h | awk '/Mem:/ {print $2}')

    DISKS=$(lsblk -o NAME,MODEL,SIZE | grep -v "NAME" | awk '{print $2, $3}')

    VIDEO=$(lshw -class display | grep -m 1 'product' | cut -d ':' -f 2 | sed 's/^[ \t]*//')

    FQDN=$(hostname -f)

    HOST_ADDRESS=$(hostname -I | awk '{print $1}')

    GATEWAY_IP=$(ip r | awk '/default/ {print $3}')

    DNS_SERVER=$(grep nameserver /etc/resolv.conf | awk '{print $2}')

    INTERFACE=$(ip a | awk '/^[0-9]+:/ {sub(/:/,"",$2); iface=$2} /^[[:space:]]*inet / {print iface, $2}')

    USERS=$(who | cut -d ' ' -f 1 | sort | uniq | tr '\n' ',' | sed 's/,$//')

    DISK_SPACE=$(df -h | awk '!/tmpfs|udev|Filesystem/ {print $6, $4}')

    PROCESS_COUNT=$(ps -e --no-headers | wc -l)

    LOAD_AVERAGES=$(uptime | grep -o "load average[s:][: ].*")
    
    MEMORY_ALLOCATION=$(free -h | awk '/Mem:/ {print $3 " / " $2}')

    LISTENING_PORTS=$(ss -tuln | awk '/LISTEN/ {print $5}' | cut -d ':' -f 2 | sort -n | uniq | tr '\n' ',' | sed 's/,$//')

    UFW_RULES=$(sudo ufw status numbered)

 cat << EOF


System Report generated by $(whoami), $(date)


System Information
------------------
Hostname: $HOSTNAME
OS: $OS
Uptime: $UPTIME


Hardware Information
--------------------
CPU: $CPU
Speed: $CPU_SPEED
RAM: $RAM
Disk(s): $DISKS
Video: $VIDEO


Network Information
-------------------
FQDN: $FQDN
Host Address: $HOST_ADDRESS
Gateway IP: $GATEWAY_IP
DNS Server: $DNS_SERVER


InterfaceName: $INTERFACE


System Status
-------------
Users Logged In: $USERS
Disk Space: $DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Memory Allocation: $MEMORY_ALLOCATION
Listening Network Ports: $LISTENING_PORTS
UFW Rules:
$UFW_RULES



EOF
